server:
  port: 8183
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.233.51.52:3306/shop?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: shop
    password: shop
    hikari:
      maximum-pool-size: 20
      minimum-idle: 8
  mail:
    host: smtp.163.com
    username: weidashan7206@163.com
    password: ERRZJXJYIHTOHDYD
  rabbitmq:
    host: 49.233.51.52
    port: 5672
    username: admin
    password: admin
  redis:
    host: 49.233.51.52
    port: 6379
    database: 1
mybatis-plus:
  type-aliases-package: com.weidashan.pojo
logging:
  level:
    cloud.weidashan.mapper: debug
minio:
  endpoint: http://49.233.51.52:9000/
  username: minioadmin
  password: minioadmin
